---
title: "Main_analyses"
author: "Joy_Fu"
date: '2022-07-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic setups
```{r Setups, message=FALSE, warning=FALSE, paged.print=FALSE}
rm(list = ls())
pacman::p_load(tidyverse, e1071, gtools)

raw_data_path = "/Users/oweyer/Documents/procedure_distance_KGE/data/"
output_path = "/Users/oweyer/Documents/procedure_distance_KGE/outputs/"
# Source in useful functions
source("/Users/oweyer/Documents/procedure_distance_KGE/code/funcs_used.R")
```

# Part 1. Clean distance metrics together
## 1. Join three metrics together and add clinical chapters
```{r}
load(file = paste0(raw_data_path, 'Embed_Dist/mod/embed_long_df.rda'))
#load(file = paste0(raw_data_path, 'Comorb_Dist/comorb_df_long.rda'))

joint_distance_full = embed_long_df %>% 
  #full_join(gen_corr_full) %>% full_join(comorb_df_long) %>% 
  #dplyr::rename(jaccard_dist = comorb_dist) %>% 
  #mutate(gen_dist = (-1)*gen_cor) %>% 
  # Add clinical chapters
  mutate(chap_clinic1 = case_when(
    substr(OPCS1, 1, 1) == "A" ~ "A Nerv Sys",
    substr(OPCS1, 1, 1) == "B" ~ "B Endocrine+Breast",
    substr(OPCS1, 1, 1) == "C" ~ "C Eye",
    substr(OPCS1, 1, 1) == "D" ~ "E Ear",
    substr(OPCS1, 1, 1) == "E" ~ "E Respiratory",
    substr(OPCS1, 1, 1) == "F" ~ "F Mouth",
    substr(OPCS1, 1, 1) == "G" ~ "G U Dig've",
    substr(OPCS1, 1, 1) == "H" ~ "H L Dig've",
    substr(OPCS1, 1, 1) == "J" ~ "J Other Abdominal",
    substr(OPCS1, 1, 1) == "K" ~ "K Heart",
    substr(OPCS1, 1, 1) == "L" ~ "L Art + Vein",
    substr(OPCS1, 1, 1) == "M" ~ "M Urinary",
    substr(OPCS1, 1, 1) == "N" ~ "N M Genital",
    substr(OPCS1, 1, 1) == "P" ~ "P Lwr F Genital",
    substr(OPCS1, 1, 1) == "Q" ~ "Q Upr F Genital",
    substr(OPCS1, 1, 1) == "R" ~ "R Preg + Birth",
    substr(OPCS1, 1, 1) == "S" ~ "S Skin",
    substr(OPCS1, 1, 1) == "T" ~ "T Soft tiss",
    substr(OPCS1, 1, 1) == "U" ~ "U Img+Test+Rehab",
    substr(OPCS1, 1, 1) == "V" ~ "V Bones of Skull+Spn",
    substr(OPCS1, 1, 1) == "W" ~ "W Othr bones+joints",
    substr(OPCS1, 1, 1) == "X" ~ "X Misc Oper'ns",
    substr(OPCS1, 1, 1) == "Y" ~ "Y Subsidiary, methods",
    substr(OPCS1, 1, 1) == "Z" ~ "Z Subsidiary, sites",
    substr(OPCS1, 1, 2) %in% c(paste0("O","0", 1:5), 'O15','O20' ) ~ "L Art + Vein",
    substr(OPCS1, 1, 2) %in% c( paste0("O","0", 6:9), 'O10', 
                               paste0("O",17:19) , 
                               paste0("O",21:27), 'O29','O32','O35',
                               paste0("O",37:40)
                               ) ~ "W Othr bones+joints",
    substr(OPCS1, 1, 2) %in% c( 'O44' ) ~ "Y Subsidiary, methods",
    substr(OPCS1, 1, 2) %in% c( paste0("O", 11:14),'O16','O28',
                               paste0("O", 30:31),
                               paste0("O", 33:34),'O36','O43','O45') ~ "Z Subsidiary, sites",
  )) %>% 
  mutate(chap_clinic2 = case_when(
    substr(OPCS2, 1, 1) == "A" ~ "A Nerv Sys",
    substr(OPCS2, 1, 1) == "B" ~ "B Endocrine+Breast",
    substr(OPCS2, 1, 1) == "C" ~ "C Eye",
    substr(OPCS2, 1, 1) == "D" ~ "E Ear",
    substr(OPCS2, 1, 1) == "E" ~ "E Respiratory",
    substr(OPCS2, 1, 1) == "F" ~ "F Mouth",
    substr(OPCS2, 1, 1) == "G" ~ "G U Dig've",
    substr(OPCS2, 1, 1) == "H" ~ "H L Dig've",
    substr(OPCS2, 1, 1) == "J" ~ "J Other Abdominal",
    substr(OPCS2, 1, 1) == "K" ~ "K Heart",
    substr(OPCS2, 1, 1) == "L" ~ "L Art + Vein",
    substr(OPCS2, 1, 1) == "M" ~ "M Urinary",
    substr(OPCS2, 1, 1) == "N" ~ "N M Genital",
    substr(OPCS2, 1, 1) == "P" ~ "P Lwr F Genital",
    substr(OPCS2, 1, 1) == "Q" ~ "Q Upr F Genital",
    substr(OPCS2, 1, 1) == "R" ~ "R Preg + Birth",
    substr(OPCS2, 1, 1) == "S" ~ "S Skin",
    substr(OPCS2, 1, 1) == "T" ~ "T Soft tiss",
    substr(OPCS2, 1, 1) == "U" ~ "U Img+Test+Rehab",
    substr(OPCS2, 1, 1) == "V" ~ "V Bones of Skull+Spn",
    substr(OPCS2, 1, 1) == "W" ~ "W Othr bones+joints",
    substr(OPCS2, 1, 1) == "X" ~ "X Misc Oper'ns",
    substr(OPCS2, 1, 1) == "Y" ~ "Y Subsidiary, methods",
    substr(OPCS2, 1, 1) == "Z" ~ "Z Subsidiary, sites",
    substr(OPCS2, 1, 2) %in% c(paste0("O","0", 1:5), 'O15','O20' ) ~ "L Art + Vein",
    substr(OPCS2, 1, 2) %in% c( paste0("O","0", 6:9), 'O10', 
                               paste0("O",17:19) , 
                               paste0("O",21:27), 'O29','O32','O35',
                               paste0("O",37:40)
                               ) ~ "W Othr bones+joints",
    substr(OPCS2, 1, 2) %in% c( 'O44' ) ~ "Y Subsidiary, methods",
    substr(OPCS2, 1, 2) %in% c( paste0("O", 11:14),'O16','O28',
                               paste0("O", 30:31),
                               paste0("O", 33:34),'O36','O43','O45') ~ "Z Subsidiary, sites",
  )) 
```

## 2. Add naive tree distance metric
```{r}
joint_distance_full_naive = joint_distance_full %>% 
  mutate(naive_dist = case_when(
    chap_clinic1 == chap_clinic2 ~ abs(as.numeric(substr(OPCS1, 2, 3)) - as.numeric(substr(OPCS2, 2, 3)))*0.01,
    TRUE ~ 1
  )) %>% unique() 
#%>% 
#  select(OPCS1, chap_clinic1, OPCS2, chap_clinic2, naive_dist, embed_dist, embed_sim, jaccard_dist, N1, N2, N_pairs, 
#         gen_dist, gen_cor, gen_cor_sd, Study_type, h2_D1, h2_D2, d1_confidence, d2_confidence)
# dim = 3960163, 19

#keep_column = c("OPCS1", "OPCS2", "chap_clinic1", "chap_clinic2", 
#                "embed_dist", "naive_dist", "jaccard_dist", "gen_dist", "Study_type")
dist_final_full = joint_distance_full_naive %>% as.data.frame() 
#%>% select(all_of(keep_column))
# dim = 3960163, 9
save(dist_final_full, file = paste0(raw_data_path, "dist_final_full.rda"))
```

## 3. Remove duplicates (A00-A01 and A01-A00)
```{r}
# Make unique pairs
dist_final_nodup = dist_final_full %>% rowwise() %>% 
  mutate(id = paste(sort(c(OPCS1, OPCS2)), collapse = "-")) %>% ungroup() %>% as.data.frame() %>% 
  filter(OPCS1 != OPCS2) %>% filter(substr(OPCS1, 3, 3) %!in% LETTERS & substr(OPCS2, 3, 3) %!in% LETTERS) %>% 
  #select(id, embed_dist, naive_dist, jaccard_dist, gen_dist, Study_type) %>% 
  unique() %>% 
  separate(id, c("OPCS1", "OPCS2"), "-")
# dim = 1963566, 7
save(dist_final_nodup, file = paste0(raw_data_path, "dist_final_nodup.rda"))
```

## 4. Output to txt files
```{r}
write.table(joint_distance_full_naive, file = paste0(output_path, "OPCS_Distance_full.txt"), 
            sep = "\t", quote = F, row.names = F, col.names = T)
write.table(dist_final_nodup, file = paste0(output_path, "OPCS_Distance_short.txt"), 
            sep = "\t", quote = F, row.names = F, col.names = T)
```


# Part 2. Check distribution - Summary statistics
## 1. Except genetic (since genetic data we have replicates due to study type issue)
```{r}
dist_final_short = dist_final_nodup %>% unique()
# N = 1,963,503
# Make a summary table  
n_sum = t(dist_final_short %>% summarise_if(is.numeric, function(x) sum(!is.na(x))))
min_sum = t(dist_final_short %>% summarise_if(is.numeric, min, na.rm = T))
max_sum = t(dist_final_short %>% summarise_if(is.numeric, max, na.rm = T))
range_sum = paste0("[", round(min_sum, 2), " - ", round(max_sum, 2), "]")
mean_sum = t(dist_final_short %>% summarise_if(is.numeric, mean, na.rm = T))
sd_sum = t(dist_final_short %>% summarise_if(is.numeric, sd, na.rm = T))
mean_sd_sum = paste0(round(mean_sum, 2), " (", round(sd_sum, 2), ")")
median_sum = t(dist_final_short %>% summarise_if(is.numeric, median, na.rm = T))
q1_sum = t(dist_final_short %>% summarise_if(is.numeric, function(x) quantile(x, 0.25, na.rm = T)))
q3_sum = t(dist_final_short %>% summarise_if(is.numeric, function(x) quantile(x, 0.75, na.rm = T)))
median_q_sum = paste0(round(median_sum, 2), " [", round(q1_sum, 2), ",", round(q3_sum, 2), "]")
summary_df = as.data.frame(cbind(n_sum, range_sum, mean_sd_sum, median_q_sum))
names(summary_df) = c("N", "Range", "Mean (SD)", "Median [1Q, 3Q]")

embed_skew = dist_final_short %>% select(embed_dist) %>% drop_na()
skewness(embed_skew$embed_dist)
```

# Part 3. Association check - embeddings vs. others
```{r}
compare_distance_df = joint_distance_full_naive %>% 
  select(OPCS1, chap_clinic1, OPCS2, chap_clinic2, naive_dist, embed_dist, 
         #jaccard_dist
         )
compare_distance_df$chap_clinic1 = factor(compare_distance_df$chap_clinic1,
                                      levels = c("I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
                                                 "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX",
                                                 "XXI", "XXII"))
compare_distance_df$chap_clinic2 = factor(compare_distance_df$chap_clinic2,
                                      levels = c("I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
                                                 "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX",
                                                 "XXI", "XXII"))
# save(compare_distance_df, file = paste0(raw_data_path, "compare_distance_df.rda"))
```

```{r}
n_count = compare_distance_df %>% 
  group_by(chap_clinic1) %>% 
  dplyr::summarise(
    n_embed = sum(!is.na(embed_dist)) 
    #, 
    #x_genetic = sum(!is.na(embed_dist) & !is.na(gen_dist)),
    #x_comorb = sum(!is.na(embed_dist) & !is.na(jaccard_dist))
    )

#cor_Spearman = compare_distance_df %>% 
#  group_by(chap_clinic1) %>% 
#  dplyr::summarise(
#    cor_gene = cor(embed_dist, gen_dist, use = "na.or.complete", method = "spearman"),
#    cor_comorb = cor(embed_dist, jaccard_dist, use = "na.or.complete", method = "spearman"),
#    cor_comorb_pearson = cor(embed_dist, jaccard_dist, use = "na.or.complete", method = "pearson"))

# Also calculate p-values
cor_vec_gene = c()
cor_vec_comorb = c()

for(i in 1:22) {
  print(i)
  chap = as.character(as.roman(i))
  cor_P_pval = compare_distance_df %>% filter(chap_clinic1 == chap & !is.na(embed_dist))
  
  cor_gene = group_cor2(cor_P_pval, "embed_dist", "gen_dist")
  cor_vec_gene = c(cor_vec_gene, cor_gene)
  cor_comorb = group_cor2(cor_P_pval, "embed_dist", "jaccard_dist")
  cor_vec_comorb = c(cor_vec_comorb, cor_comorb)
  
}

cor_Spearman_P = as.data.frame(cbind(cor_vec_gene, cor_vec_comorb))

cor_Embedresult_byChap = cbind(n_count, cor_Spearman[,2:3], cor_Spearman_P)
colnames(cor_Embedresult_byChap) = c("Chapter", "n_embed", "complete_genetic", "complete_comorb", 
                                "cor_gene", "cor_comorb", "cor_gene_p", "cor_comorb_p")
```
