---
title: "Embedding-based Disease Distance Metric"
author: "Joy_Fu"
date: '2022-07-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic setups
```{r Setups, message=FALSE, warning=FALSE, paged.print=FALSE}
rm(list = ls())
pacman::p_load(tidyverse, readr, WGCNA, cluster, fossil, moduleColor)

raw_data_path = "/Users/oweyer/Documents/procedure_distance_KGE/data/"
output_path = "/Users/oweyer/Documents/procedure_distance_KGE/outputs/"
# Source in useful functions
source("/Users/oweyer/Documents/procedure_distance_KGE/code/funcs_used.R")
```

# Part 1. Calculate embedding similarity
This will take a long time, already generated the final outputs in the data folder.
```{r}
source("/Users/oweyer/Documents/procedure_distance_KGE/code/Embed_Dist/1.1_RV_embedding_similarity.R")
# Output file: /Users/Mingzhou/Desktop/Projects/Disease.Similarity/GitHub/data/Embed_Dist/mod/embed_sim.rda
```

# Part 2. Data Cleaning
```{r}
load(file = paste0(raw_data_path, 'Embed_Dist/mod/embed_sim_opcs.rda'))
dim(embed_sim)
# We first want to calibrate the RV coefficients to [0,1]
embed_sim_cal = range01(embed_sim)
# Get long format (pairwise distance)
embed_sim_full = makeSymm(embed_sim_cal)
embed_long = reshape2::melt(embed_sim_full)
colnames(embed_long) = c("OPCS1", "OPCS2", "embed_sim")
embed_long_df = embed_long %>% as.data.frame() %>% 
  mutate(embed_dist = 1 - embed_sim)
save(embed_long_df, file = paste0(raw_data_path, 'Embed_Dist/mod/embed_long_df.rda'))
```

# Part 3. Clustering
## 1. Hierarchical static cut tree
```{r}
embed.dist = as.dist(1 - embed_sim_cal)
consTree = hclust(embed.dist, method = "complete")
# Hierarchical tree only
hclusters = cutree(consTree, k = 22)
table(hclusters)
```

## 2. K-medoids
```{r}
embed.kmedoids = pam(embed.dist, 22) # create k-medoids clustering with 22 clusters
kclusters = embed.kmedoids$cluster
table(kclusters)
```

## 3. Hierarchical dynamic cut trees
```{r}
# WGCNA w/ Dynamic Tree Cut
# Set min module size -- here we set the number to which can result in 22 clusters
minModuleSize = 41
unmergedLabels = cutreeDynamic(dendro = consTree, cutHeight = NULL,
                               distM = 1 - embed_sim_full,
                               minClusterSize = minModuleSize)
unmergedColors = moduleColor::labels2colors(unmergedLabels)
table(unmergedLabels)
```

## 4. Evaluation of clustering results
### 1) Record clustering results
```{r Record the cluster results}

charToRawVec <- Vectorize(FUN = charToRaw, vectorize.args = "x")


cluster_result = cbind(colnames(embed_sim_cal), hclusters, kclusters, unmergedLabels, unmergedColors)
colnames(cluster_result) = c("OPCS", "hcluster_embed", "kcluster_embed", "dtcluster_embed", "dtcolor_embed")
cluster_result_addChap = cluster_result %>% as.data.frame() %>% 
  mutate(chap_clinic = case_when(
    substr(OPCS, 1, 1) == "A" ~ "A Nerv Sys",
    substr(OPCS, 1, 1) == "B" ~ "B Endocrine+Breast",
    substr(OPCS, 1, 1) == "C" ~ "C Eye",
    substr(OPCS, 1, 1) == "D" ~ "E Ear",
    substr(OPCS, 1, 1) == "E" ~ "E Respiratory",
    substr(OPCS, 1, 1) == "F" ~ "F Mouth",
    substr(OPCS, 1, 1) == "G" ~ "G U Dig've",
    substr(OPCS, 1, 1) == "H" ~ "H L Dig've",
    substr(OPCS, 1, 1) == "J" ~ "J Other Abdominal",
    substr(OPCS, 1, 1) == "K" ~ "K Heart",
    substr(OPCS, 1, 1) == "L" ~ "L Art + Vein",
    substr(OPCS, 1, 1) == "M" ~ "M Urinary",
    substr(OPCS, 1, 1) == "N" ~ "N M Genital",
    substr(OPCS, 1, 1) == "P" ~ "P Lwr F Genital",
    substr(OPCS, 1, 1) == "Q" ~ "Q Upr F Genital",
    substr(OPCS, 1, 1) == "R" ~ "R Preg + Birth",
    substr(OPCS, 1, 1) == "S" ~ "S Skin",
    substr(OPCS, 1, 1) == "T" ~ "T Soft tiss",
    substr(OPCS, 1, 1) == "U" ~ "U Img+Test+Rehab",
    substr(OPCS, 1, 1) == "V" ~ "V Bones of Skull+Spn",
    substr(OPCS, 1, 1) == "W" ~ "W Othr bones+joints",
    substr(OPCS, 1, 1) == "X" ~ "X Misc Oper'ns",
    substr(OPCS, 1, 1) == "Y" ~ "Y Subsidiary, methods",
    substr(OPCS, 1, 1) == "Z" ~ "Z Subsidiary, sites",
    substr(OPCS, 1, 2) %in% c(paste0("O","0", 1:5), 'O15','O20' ) ~ "L Art + Vein",
    substr(OPCS, 1, 2) %in% c( paste0("O","0", 6:9), 'O10', 
                               paste0("O",17:19) , 
                               paste0("O",21:27), 'O29','O32','O35',
                               paste0("O",37:40)
                               ) ~ "W Othr bones+joints",
    substr(OPCS, 1, 2) %in% c( 'O44' ) ~ "Y Subsidiary, methods",
    substr(OPCS, 1, 2) %in% c( paste0("O", 11:14),'O16','O28',
                               paste0("O", 30:31),
                               paste0("O", 33:34),'O36','O43','O45') ~ "Z Subsidiary, sites",
  )) %>% 
  mutate(chapter_num =as.integer(charToRawVec( chap_clinic %>% substr(1,1) ))) %>% 
  mutate_at(c("hcluster_embed", "kcluster_embed", "dtcluster_embed"), as.numeric)

# Output results to table
write.table(cluster_result, file = paste0(output_path, "OPCS_embed_cluster_results.txt"), 
            sep = "\t", quote = F, row.names = F, col.names = T)
# save(cluster_result, file = paste0(raw_data_path, "Embed_Dist/mod/cluster_result.rda"))
```

### 2) Rand index
```{r Rand index calculation}
# Calculate rand index
rand_hcluster_e = rand.index(cluster_result_addChap$hcluster_embed, cluster_result_addChap$chapter_num)
rand_kmed_e = rand.index(cluster_result_addChap$kcluster_embed, cluster_result_addChap$chapter_num)
rand_dtc_e = rand.index(cluster_result_addChap$dtcluster_embed, cluster_result_addChap$chapter_num)

results_cluster = c(rand_hcluster_e, rand_kmed_e, rand_dtc_e)
results_cluster
```



